version: '3.8'

services:
  # OpenVidu 서버 - 개발용 설정
  openvidu-server:
    image: openvidu/openvidu-dev:2.30.0
    container_name: openvidu-server-dev
    restart: unless-stopped
    environment:
      # 기본 설정
      - OPENVIDU_SECRET=MY_SECRET
      - OPENVIDU_DOMAIN_OR_PUBLIC_IP=localhost
      - OPENVIDU_PORT=4443
      
      # 개발 환경 설정
      - OPENVIDU_RECORDING=true
      - OPENVIDU_RECORDING_PATH=/opt/openvidu/recordings
      - OPENVIDU_RECORDING_PUBLIC_ACCESS=true
      - OPENVIDU_RECORDING_NOTIFICATION=publisher_moderator
      - OPENVIDU_RECORDING_AUTOSTOP_TIMEOUT=120
      - OPENVIDU_STREAMS_VIDEO_MAX_RECV_BANDWIDTH=1000
      - OPENVIDU_STREAMS_VIDEO_MIN_RECV_BANDWIDTH=300
      - OPENVIDU_STREAMS_VIDEO_MAX_SEND_BANDWIDTH=1000
      - OPENVIDU_STREAMS_VIDEO_MIN_SEND_BANDWIDTH=300
      
      # 보안 설정 (개발용)
      - CERTIFICATE_TYPE=selfsigned
      
      # 로깅 설정
      - OV_CE_DEBUG_LEVEL=INFO
      
      # WebRTC 설정 (포트 범위 더욱 축소)
      - KMS_MIN_PORT=50000
      - KMS_MAX_PORT=50020
      
      # 개발 편의를 위한 설정
      - OPENVIDU_WEBHOOK=false
      - OPENVIDU_CDR=false
    
    ports:
      - "25565:4443"  # OpenVidu HTTP/HTTPS 포트
      - "50000-50020:50000-50020/udp"  # WebRTC 미디어 포트 범위
    
    volumes:
      - openvidu_data:/opt/openvidu
      - openvidu_recordings:/opt/openvidu/recordings
      - /var/run/docker.sock:/var/run/docker.sock
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:25565/openvidu/api/config"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  openvidu_data:
    driver: local
  openvidu_recordings:
    driver: local

networks:
  default:
    driver: bridge