# dev 서버환경 전용 설정
app:
  oauth2:
    authorized-redirect-uri: ${FRONTEND_URL}/oauth2/redirect  # 프론트엔드로 리다이렉트
  cookie:
    domain: ${COOKIE_DOMAIN:.coffeechat.kro.kr}  # dev 서버 쿠키 도메인
    same-site: ${COOKIE_SAMESITE:Lax}