# 로컬 개발환경 전용 설정
app:
  oauth2:
    authorized-redirect-uri: http://localhost:8080/swagger-ui/index.html  # OAuth 성공 후 Swagger로 리다이렉트
  cookie:
    domain: ${COOKIE_DOMAIN:}  # 로컬에서는 쿠키 도메인 없음
    same-site: ${COOKIE_SAMESITE:Lax}

spring:
  cloud:
    gcp:
      credentials:
        location: "${GCP_CREDENTIALS_JSON_PATH}"
  # init.sql 자동 실행 설정 (로컬 전용)
  sql:
    init:
      mode: always
      data-locations: classpath:init.sql
      continue-on-error: true
  jpa:
    defer-datasource-initialization: true
