### 1. 루키 테스트 계정 생성
POST http://localhost:8080/api/test/auth/create-rookie
Content-Type: application/json

### 2. 가이드 테스트 계정 생성
POST http://localhost:8080/api/test/auth/create-guide
Content-Type: application/json

### 3. 테스트 계정 로그인 (🔥🔥🔥🔥🔥🔥1번 또는 2번으로 새로 생성된 계정의 닉네임을 수동으로 입력해야 함🔥🔥🔥🔥🔥🔥)
POST http://localhost:8080/api/test/auth/login
Content-Type: application/json

{
  "nickname": "guide_dba003c7"
}

### 4. JWT 토큰으로 내 정보 조회 테스트 (3번 에서 받은 accessToken을 Bearer 뒤에 붙여넣기, 다른 도메인에서도 token 사용 가능한지 확인용)
GET http://localhost:8080/api/member/me
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlM2FjYjcwZCIsInR5cGUiOiJhY2Nlc3MiLCJqdGkiOiI5ZjZhMWQ1NS03OWU5LTRlMjEtYWI0ZS0zYTk1NDRkYmQ3NDIiLCJpYXQiOjE3NTY1NjA0NzIsImV4cCI6MTc1NjU2MjI3Mn0.KHAQC3Nv9OfP6u029YEoUK8mOGf4TT62ZdSSmxKF7vbfGZLmqUPsgNSoFDTGI0ZMATG9B2P5HsBcNO7PrvBT0g

### 5. 테스트 계정 일괄 삭제
DELETE http://localhost:8080/api/test/auth/cleanup


### 6. 가이드 본인 프로필 조회
GET http://localhost:8080/api/guides/me
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlM2FjYjcwZCIsInR5cGUiOiJhY2Nlc3MiLCJqdGkiOiJmNTI0YzIxMi1mYjM0LTRhMTUtYmFhYi0zMzA4ZjY5NjE5M2EiLCJpYXQiOjE3NTY1NjA1ODMsImV4cCI6MTc1NjU2MjM4M30.7aPhVRM3YPi8n81EqL6oJJrECysATkIp4tHCFi9yokf3cNONWAbIpW59rOLS7uPKIDEO2onrO3fowdsBIKPn7Q
